// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AndriFannarUmfn.ksiRefrence {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="motSoap", Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class mot : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MotLeikirOperationCompleted;
        
        private System.Threading.SendOrPostCallback MotStadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MotMarkahaestuOperationCompleted;
        
        private System.Threading.SendOrPostCallback FelogLeikirOperationCompleted;
        
        private System.Threading.SendOrPostCallback FlokkurOperationCompleted;
        
        private System.Threading.SendOrPostCallback MotSpjoldGulOperationCompleted;
        
        private System.Threading.SendOrPostCallback MotSpjoldRaudOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeikurAtburdirOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeikurLeikmennOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeikurDomararOperationCompleted;
        
        /// CodeRemarks
        public mot() {
            this.Url = "http://www2.ksi.is/vefthjonustur/mot.asmx";
        }
        
        public mot(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event MotLeikirCompletedEventHandler MotLeikirCompleted;
        
        /// CodeRemarks
        public event MotStadaCompletedEventHandler MotStadaCompleted;
        
        /// CodeRemarks
        public event MotMarkahaestuCompletedEventHandler MotMarkahaestuCompleted;
        
        /// CodeRemarks
        public event FelogLeikirCompletedEventHandler FelogLeikirCompleted;
        
        /// CodeRemarks
        public event FlokkurCompletedEventHandler FlokkurCompleted;
        
        /// CodeRemarks
        public event MotSpjoldGulCompletedEventHandler MotSpjoldGulCompleted;
        
        /// CodeRemarks
        public event MotSpjoldRaudCompletedEventHandler MotSpjoldRaudCompleted;
        
        /// CodeRemarks
        public event LeikurAtburdirCompletedEventHandler LeikurAtburdirCompleted;
        
        /// CodeRemarks
        public event LeikurLeikmennCompletedEventHandler LeikurLeikmennCompleted;
        
        /// CodeRemarks
        public event LeikurDomararCompletedEventHandler LeikurDomararCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www2.ksi.is/vefthjonustur/mot/MotLeikir", RequestNamespace="http://www2.ksi.is/vefthjonustur/mot/", ResponseNamespace="http://www2.ksi.is/vefthjonustur/mot/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("MotLeikirSvar")]
        public MotLeikirSvar MotLeikir(string MotNumer) {
            object[] results = this.Invoke("MotLeikir", new object[] {
                        MotNumer});
            return ((MotLeikirSvar)(results[0]));
        }
        
        /// CodeRemarks
        public void MotLeikirAsync(string MotNumer) {
            this.MotLeikirAsync(MotNumer, null);
        }
        
        /// CodeRemarks
        public void MotLeikirAsync(string MotNumer, object userState) {
            if ((this.MotLeikirOperationCompleted == null)) {
                this.MotLeikirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMotLeikirOperationCompleted);
            }
            this.InvokeAsync("MotLeikir", new object[] {
                        MotNumer}, this.MotLeikirOperationCompleted, userState);
        }
        
        private void OnMotLeikirOperationCompleted(object arg) {
            if ((this.MotLeikirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MotLeikirCompleted(this, new MotLeikirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www2.ksi.is/vefthjonustur/mot/MotStada", RequestNamespace="http://www2.ksi.is/vefthjonustur/mot/", ResponseNamespace="http://www2.ksi.is/vefthjonustur/mot/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("MotStadaSvar")]
        public MotStadaSvar MotStada(string MotNumer) {
            object[] results = this.Invoke("MotStada", new object[] {
                        MotNumer});
            return ((MotStadaSvar)(results[0]));
        }
        
        /// CodeRemarks
        public void MotStadaAsync(string MotNumer) {
            this.MotStadaAsync(MotNumer, null);
        }
        
        /// CodeRemarks
        public void MotStadaAsync(string MotNumer, object userState) {
            if ((this.MotStadaOperationCompleted == null)) {
                this.MotStadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMotStadaOperationCompleted);
            }
            this.InvokeAsync("MotStada", new object[] {
                        MotNumer}, this.MotStadaOperationCompleted, userState);
        }
        
        private void OnMotStadaOperationCompleted(object arg) {
            if ((this.MotStadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MotStadaCompleted(this, new MotStadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www2.ksi.is/vefthjonustur/mot/MotMarkahaestu", RequestNamespace="http://www2.ksi.is/vefthjonustur/mot/", ResponseNamespace="http://www2.ksi.is/vefthjonustur/mot/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("MotMarkahaestuSvar")]
        public MotMarkahaestuSvar MotMarkahaestu(string MotNumer) {
            object[] results = this.Invoke("MotMarkahaestu", new object[] {
                        MotNumer});
            return ((MotMarkahaestuSvar)(results[0]));
        }
        
        /// CodeRemarks
        public void MotMarkahaestuAsync(string MotNumer) {
            this.MotMarkahaestuAsync(MotNumer, null);
        }
        
        /// CodeRemarks
        public void MotMarkahaestuAsync(string MotNumer, object userState) {
            if ((this.MotMarkahaestuOperationCompleted == null)) {
                this.MotMarkahaestuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMotMarkahaestuOperationCompleted);
            }
            this.InvokeAsync("MotMarkahaestu", new object[] {
                        MotNumer}, this.MotMarkahaestuOperationCompleted, userState);
        }
        
        private void OnMotMarkahaestuOperationCompleted(object arg) {
            if ((this.MotMarkahaestuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MotMarkahaestuCompleted(this, new MotMarkahaestuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www2.ksi.is/vefthjonustur/mot/FelogLeikir", RequestNamespace="http://www2.ksi.is/vefthjonustur/mot/", ResponseNamespace="http://www2.ksi.is/vefthjonustur/mot/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("FelogLeikirSvar")]
        public FelogLeikirSvar FelogLeikir(string FelagNumer, string VollurNumer, string FlokkurNumer, string Kyn, System.DateTime DagsFra, System.DateTime DagsTil) {
            object[] results = this.Invoke("FelogLeikir", new object[] {
                        FelagNumer,
                        VollurNumer,
                        FlokkurNumer,
                        Kyn,
                        DagsFra,
                        DagsTil});
            return ((FelogLeikirSvar)(results[0]));
        }
        
        /// CodeRemarks
        public void FelogLeikirAsync(string FelagNumer, string VollurNumer, string FlokkurNumer, string Kyn, System.DateTime DagsFra, System.DateTime DagsTil) {
            this.FelogLeikirAsync(FelagNumer, VollurNumer, FlokkurNumer, Kyn, DagsFra, DagsTil, null);
        }
        
        /// CodeRemarks
        public void FelogLeikirAsync(string FelagNumer, string VollurNumer, string FlokkurNumer, string Kyn, System.DateTime DagsFra, System.DateTime DagsTil, object userState) {
            if ((this.FelogLeikirOperationCompleted == null)) {
                this.FelogLeikirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFelogLeikirOperationCompleted);
            }
            this.InvokeAsync("FelogLeikir", new object[] {
                        FelagNumer,
                        VollurNumer,
                        FlokkurNumer,
                        Kyn,
                        DagsFra,
                        DagsTil}, this.FelogLeikirOperationCompleted, userState);
        }
        
        private void OnFelogLeikirOperationCompleted(object arg) {
            if ((this.FelogLeikirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FelogLeikirCompleted(this, new FelogLeikirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www2.ksi.is/vefthjonustur/mot/Flokkur", RequestNamespace="http://www2.ksi.is/vefthjonustur/mot/", ResponseNamespace="http://www2.ksi.is/vefthjonustur/mot/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("FlokkurSvar")]
        public FlokkurSvar Flokkur() {
            object[] results = this.Invoke("Flokkur", new object[0]);
            return ((FlokkurSvar)(results[0]));
        }
        
        /// CodeRemarks
        public void FlokkurAsync() {
            this.FlokkurAsync(null);
        }
        
        /// CodeRemarks
        public void FlokkurAsync(object userState) {
            if ((this.FlokkurOperationCompleted == null)) {
                this.FlokkurOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFlokkurOperationCompleted);
            }
            this.InvokeAsync("Flokkur", new object[0], this.FlokkurOperationCompleted, userState);
        }
        
        private void OnFlokkurOperationCompleted(object arg) {
            if ((this.FlokkurCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FlokkurCompleted(this, new FlokkurCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www2.ksi.is/vefthjonustur/mot/MotSpjoldGul", RequestNamespace="http://www2.ksi.is/vefthjonustur/mot/", ResponseNamespace="http://www2.ksi.is/vefthjonustur/mot/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("MotSpjoldSvar")]
        public MotSpjoldSvar MotSpjoldGul(string MotNumer) {
            object[] results = this.Invoke("MotSpjoldGul", new object[] {
                        MotNumer});
            return ((MotSpjoldSvar)(results[0]));
        }
        
        /// CodeRemarks
        public void MotSpjoldGulAsync(string MotNumer) {
            this.MotSpjoldGulAsync(MotNumer, null);
        }
        
        /// CodeRemarks
        public void MotSpjoldGulAsync(string MotNumer, object userState) {
            if ((this.MotSpjoldGulOperationCompleted == null)) {
                this.MotSpjoldGulOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMotSpjoldGulOperationCompleted);
            }
            this.InvokeAsync("MotSpjoldGul", new object[] {
                        MotNumer}, this.MotSpjoldGulOperationCompleted, userState);
        }
        
        private void OnMotSpjoldGulOperationCompleted(object arg) {
            if ((this.MotSpjoldGulCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MotSpjoldGulCompleted(this, new MotSpjoldGulCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www2.ksi.is/vefthjonustur/mot/MotSpjoldRaud", RequestNamespace="http://www2.ksi.is/vefthjonustur/mot/", ResponseNamespace="http://www2.ksi.is/vefthjonustur/mot/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("MotSpjoldSvar")]
        public MotSpjoldSvar MotSpjoldRaud(string MotNumer) {
            object[] results = this.Invoke("MotSpjoldRaud", new object[] {
                        MotNumer});
            return ((MotSpjoldSvar)(results[0]));
        }
        
        /// CodeRemarks
        public void MotSpjoldRaudAsync(string MotNumer) {
            this.MotSpjoldRaudAsync(MotNumer, null);
        }
        
        /// CodeRemarks
        public void MotSpjoldRaudAsync(string MotNumer, object userState) {
            if ((this.MotSpjoldRaudOperationCompleted == null)) {
                this.MotSpjoldRaudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMotSpjoldRaudOperationCompleted);
            }
            this.InvokeAsync("MotSpjoldRaud", new object[] {
                        MotNumer}, this.MotSpjoldRaudOperationCompleted, userState);
        }
        
        private void OnMotSpjoldRaudOperationCompleted(object arg) {
            if ((this.MotSpjoldRaudCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MotSpjoldRaudCompleted(this, new MotSpjoldRaudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www2.ksi.is/vefthjonustur/mot/LeikurAtburdir", RequestNamespace="http://www2.ksi.is/vefthjonustur/mot/", ResponseNamespace="http://www2.ksi.is/vefthjonustur/mot/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("LeikurAtburdurSvar")]
        public LeikurAtburdirSvar LeikurAtburdir(string LeikurNumer) {
            object[] results = this.Invoke("LeikurAtburdir", new object[] {
                        LeikurNumer});
            return ((LeikurAtburdirSvar)(results[0]));
        }
        
        /// CodeRemarks
        public void LeikurAtburdirAsync(string LeikurNumer) {
            this.LeikurAtburdirAsync(LeikurNumer, null);
        }
        
        /// CodeRemarks
        public void LeikurAtburdirAsync(string LeikurNumer, object userState) {
            if ((this.LeikurAtburdirOperationCompleted == null)) {
                this.LeikurAtburdirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeikurAtburdirOperationCompleted);
            }
            this.InvokeAsync("LeikurAtburdir", new object[] {
                        LeikurNumer}, this.LeikurAtburdirOperationCompleted, userState);
        }
        
        private void OnLeikurAtburdirOperationCompleted(object arg) {
            if ((this.LeikurAtburdirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeikurAtburdirCompleted(this, new LeikurAtburdirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www2.ksi.is/vefthjonustur/mot/LeikurLeikmenn", RequestNamespace="http://www2.ksi.is/vefthjonustur/mot/", ResponseNamespace="http://www2.ksi.is/vefthjonustur/mot/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("LeikurLeikmennSvar")]
        public LeikurLeikmennSvar LeikurLeikmenn(string LeikurNumer) {
            object[] results = this.Invoke("LeikurLeikmenn", new object[] {
                        LeikurNumer});
            return ((LeikurLeikmennSvar)(results[0]));
        }
        
        /// CodeRemarks
        public void LeikurLeikmennAsync(string LeikurNumer) {
            this.LeikurLeikmennAsync(LeikurNumer, null);
        }
        
        /// CodeRemarks
        public void LeikurLeikmennAsync(string LeikurNumer, object userState) {
            if ((this.LeikurLeikmennOperationCompleted == null)) {
                this.LeikurLeikmennOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeikurLeikmennOperationCompleted);
            }
            this.InvokeAsync("LeikurLeikmenn", new object[] {
                        LeikurNumer}, this.LeikurLeikmennOperationCompleted, userState);
        }
        
        private void OnLeikurLeikmennOperationCompleted(object arg) {
            if ((this.LeikurLeikmennCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeikurLeikmennCompleted(this, new LeikurLeikmennCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www2.ksi.is/vefthjonustur/mot/LeikurDomarar", RequestNamespace="http://www2.ksi.is/vefthjonustur/mot/", ResponseNamespace="http://www2.ksi.is/vefthjonustur/mot/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("LeikurDomararSvar")]
        public LeikurDomararSvar LeikurDomarar(string LeikurNumer) {
            object[] results = this.Invoke("LeikurDomarar", new object[] {
                        LeikurNumer});
            return ((LeikurDomararSvar)(results[0]));
        }
        
        /// CodeRemarks
        public void LeikurDomararAsync(string LeikurNumer) {
            this.LeikurDomararAsync(LeikurNumer, null);
        }
        
        /// CodeRemarks
        public void LeikurDomararAsync(string LeikurNumer, object userState) {
            if ((this.LeikurDomararOperationCompleted == null)) {
                this.LeikurDomararOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeikurDomararOperationCompleted);
            }
            this.InvokeAsync("LeikurDomarar", new object[] {
                        LeikurNumer}, this.LeikurDomararOperationCompleted, userState);
        }
        
        private void OnLeikurDomararOperationCompleted(object arg) {
            if ((this.LeikurDomararCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeikurDomararCompleted(this, new LeikurDomararCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class MotLeikirSvar {
        
        /// <remarks/>
        public MotLeikur[] ArrayMotLeikir;
        
        /// <remarks/>
        public int VillaNumer;
        
        /// <remarks/>
        public string Villa;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class MotLeikur {
        
        /// <remarks/>
        public int LeikurNumer;
        
        /// <remarks/>
        public string UmferdNumer;
        
        /// <remarks/>
        public System.DateTime LeikDagur;
        
        /// <remarks/>
        public string FelagHeimaNafn;
        
        /// <remarks/>
        public int FelagHeimaNumer;
        
        /// <remarks/>
        public string FelagUtiNafn;
        
        /// <remarks/>
        public int FelagUtiNumer;
        
        /// <remarks/>
        public string UrslitHeima;
        
        /// <remarks/>
        public string UrslitUti;
        
        /// <remarks/>
        public string StadaFyrriHalfleikHeima;
        
        /// <remarks/>
        public string StadaFyrriHalfleikUti;
        
        /// <remarks/>
        public string StadaSeinniHalfleikHeima;
        
        /// <remarks/>
        public string StadaSeinniHalfLeikUti;
        
        /// <remarks/>
        public string SkyrslaStada;
        
        /// <remarks/>
        public string VollurNafn;
        
        /// <remarks/>
        public string Ahorfendur;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class LeikurDomarar {
        
        /// <remarks/>
        public int DomariNumer;
        
        /// <remarks/>
        public string DomariNafn;
        
        /// <remarks/>
        public int HlutverkNumer;
        
        /// <remarks/>
        public string HlutverkNafn;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class LeikurDomararSvar {
        
        /// <remarks/>
        public LeikurDomarar[] ArrayLeikurDomarar;
        
        /// <remarks/>
        public int VillaNumer;
        
        /// <remarks/>
        public string Villa;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class LeikurLeikmenn {
        
        /// <remarks/>
        public int LeikmadurNumer;
        
        /// <remarks/>
        public string LeikmadurNafn;
        
        /// <remarks/>
        public int FelagNumer;
        
        /// <remarks/>
        public string FelagNafn;
        
        /// <remarks/>
        public string TreyjuNumer;
        
        /// <remarks/>
        public int StadaNumer;
        
        /// <remarks/>
        public string StadaNafn;
        
        /// <remarks/>
        public int Leikmadur;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class LeikurLeikmennSvar {
        
        /// <remarks/>
        public LeikurLeikmenn[] ArrayLeikurLeikmenn;
        
        /// <remarks/>
        public int VillaNumer;
        
        /// <remarks/>
        public string Villa;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class LeikurAtburdir {
        
        /// <remarks/>
        public int LeikmadurNumer;
        
        /// <remarks/>
        public string LeikmadurNafn;
        
        /// <remarks/>
        public int FelagNumer;
        
        /// <remarks/>
        public string FelagNafn;
        
        /// <remarks/>
        public int TreyjuNumer;
        
        /// <remarks/>
        public int AtburdurMinuta;
        
        /// <remarks/>
        public int AtburdurNumer;
        
        /// <remarks/>
        public string AtburdurNafn;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class LeikurAtburdirSvar {
        
        /// <remarks/>
        public LeikurAtburdir[] ArrayLeikurAtburdir;
        
        /// <remarks/>
        public int VillaNumer;
        
        /// <remarks/>
        public string Villa;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class MotSpjold {
        
        /// <remarks/>
        public int LeikmadurNumer;
        
        /// <remarks/>
        public string LeikmadurNafn;
        
        /// <remarks/>
        public string FelagNafn;
        
        /// <remarks/>
        public int Fjoldi;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class MotSpjoldSvar {
        
        /// <remarks/>
        public MotSpjold[] ArrayMotSpjold;
        
        /// <remarks/>
        public int VillaNumer;
        
        /// <remarks/>
        public string Villa;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class Flokkur {
        
        /// <remarks/>
        public string FlokkurHeiti;
        
        /// <remarks/>
        public int FlokkurNumer;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class FlokkurSvar {
        
        /// <remarks/>
        public Flokkur[] ArrayFlokkur;
        
        /// <remarks/>
        public int VillaNumer;
        
        /// <remarks/>
        public string Villa;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class FelogLeikir {
        
        /// <remarks/>
        public int LeikurNumer;
        
        /// <remarks/>
        public System.DateTime LeikDagur;
        
        /// <remarks/>
        public string FelagHeimaNafn;
        
        /// <remarks/>
        public int FelagHeimaNumer;
        
        /// <remarks/>
        public string FelagUtiNafn;
        
        /// <remarks/>
        public int FelagUtiNumer;
        
        /// <remarks/>
        public string UrslitHeima;
        
        /// <remarks/>
        public string UrslitUti;
        
        /// <remarks/>
        public string SkyrslaStada;
        
        /// <remarks/>
        public string VollurNafn;
        
        /// <remarks/>
        public int VollurNumer;
        
        /// <remarks/>
        public string MotNafn;
        
        /// <remarks/>
        public int MotNumer;
        
        /// <remarks/>
        public string Flokkur;
        
        /// <remarks/>
        public int MotKyn;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class FelogLeikirSvar {
        
        /// <remarks/>
        public FelogLeikir[] ArrayFelogLeikir;
        
        /// <remarks/>
        public int VillaNumer;
        
        /// <remarks/>
        public string Villa;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class MotMarkahaestu {
        
        /// <remarks/>
        public int LeikmadurNumer;
        
        /// <remarks/>
        public string LeikmadurNafn;
        
        /// <remarks/>
        public string FelagNafn;
        
        /// <remarks/>
        public int Mork;
        
        /// <remarks/>
        public int Viti;
        
        /// <remarks/>
        public int Leikir;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class MotMarkahaestuSvar {
        
        /// <remarks/>
        public MotMarkahaestu[] ArrayMotMarkahaestu;
        
        /// <remarks/>
        public int VillaNumer;
        
        /// <remarks/>
        public string Villa;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class MotStada {
        
        /// <remarks/>
        public int FelagNumer;
        
        /// <remarks/>
        public string FelagNafn;
        
        /// <remarks/>
        public int LeikirAlls;
        
        /// <remarks/>
        public int LeikirUnnir;
        
        /// <remarks/>
        public int LeikirJafnt;
        
        /// <remarks/>
        public int LeikirTap;
        
        /// <remarks/>
        public int MorkSkorud;
        
        /// <remarks/>
        public int MorkFenginASig;
        
        /// <remarks/>
        public int MorkMisMunur;
        
        /// <remarks/>
        public int Stig;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www2.ksi.is/vefthjonustur/mot/")]
    public partial class MotStadaSvar {
        
        /// <remarks/>
        public MotStada[] ArrayMotStada;
        
        /// <remarks/>
        public int VillaNumer;
        
        /// <remarks/>
        public string Villa;
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void MotLeikirCompletedEventHandler(object sender, MotLeikirCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MotLeikirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MotLeikirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public MotLeikirSvar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MotLeikirSvar)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void MotStadaCompletedEventHandler(object sender, MotStadaCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MotStadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MotStadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public MotStadaSvar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MotStadaSvar)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void MotMarkahaestuCompletedEventHandler(object sender, MotMarkahaestuCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MotMarkahaestuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MotMarkahaestuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public MotMarkahaestuSvar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MotMarkahaestuSvar)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void FelogLeikirCompletedEventHandler(object sender, FelogLeikirCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FelogLeikirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FelogLeikirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public FelogLeikirSvar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FelogLeikirSvar)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void FlokkurCompletedEventHandler(object sender, FlokkurCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FlokkurCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FlokkurCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public FlokkurSvar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FlokkurSvar)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void MotSpjoldGulCompletedEventHandler(object sender, MotSpjoldGulCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MotSpjoldGulCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MotSpjoldGulCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public MotSpjoldSvar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MotSpjoldSvar)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void MotSpjoldRaudCompletedEventHandler(object sender, MotSpjoldRaudCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MotSpjoldRaudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MotSpjoldRaudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public MotSpjoldSvar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MotSpjoldSvar)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void LeikurAtburdirCompletedEventHandler(object sender, LeikurAtburdirCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeikurAtburdirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeikurAtburdirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public LeikurAtburdirSvar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LeikurAtburdirSvar)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void LeikurLeikmennCompletedEventHandler(object sender, LeikurLeikmennCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeikurLeikmennCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeikurLeikmennCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public LeikurLeikmennSvar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LeikurLeikmennSvar)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void LeikurDomararCompletedEventHandler(object sender, LeikurDomararCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeikurDomararCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeikurDomararCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public LeikurDomararSvar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LeikurDomararSvar)(this.results[0]));
            }
        }
    }
}
